#!/bin/bash

set -e

# Build signatures and functions
if [ "$1" = "build" ]; then
    # Install native dependencies
    apt update
    apt install -y curl make git

    # Install Scale
    curl -fsSL https://dl.scale.sh?analytics=false | sh
    source ~/.bashrc

    # Install TinyGo
    curl -L -o /tmp/tinygo.tar.gz https://github.com/tinygo-org/tinygo/releases/download/v0.29.0/tinygo0.29.0.linux-amd64.tar.gz
    mkdir -p /opt
    tar xvzf /tmp/tinygo.tar.gz -C /opt
    export PATH=$PATH:/opt/tinygo/bin

    # Install Rust
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
    source ~/.cargo/env
    rustup target add wasm32-wasi

    # Configure Git
    git config --global --add safe.directory '*'

    # Generate dependencies
    make depend/signature

    # Build
    make

    exit 0
fi
